Broken code, saving for later
Broken kode don't download. setContent is acting up. I don't know why.

Got this error:

FATAL EXCEPTION: main
                                                                                                    Process: com.example.shelfship, PID: 12437
                                                                                                    java.lang.NoSuchMethodError: No static method setContent$default(Landroidx/activity/ComponentActivity;Landroidx/compose/runtime/CompositionContext;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)V in class Landroidx/activity/compose/ComponentActivityKt; or its super classes (declaration of 'androidx.activity.compose.ComponentActivityKt' appears in /data/app/~~h2YpKkPPvLo-ObJzIYLQnw==/com.example.shelfship-GAjKKagUb6uznhruAMVmFA==/base.apk)
                                                                                                    	at com.example.shelfship.views.MainActivity.onCreate(MainActivity.kt:17)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:9140)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:9118)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1505)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4217)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4422)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2782)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:248)
                                                                                                    	at android.os.Looper.loop(Looper.java:338)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8982)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
---------------------------- PROCESS ENDED (12437) for package com

Tried to fix it and got this:

Compose Compiler Gradle plugin is required' in Kotlin 1.9 project?

I'm going to push in case I can reuse something. Otherwise I'll just clean branch again.